apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: ghaulp
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  schedule: "*/5 * * * *"
  env:
    - name: GITHUB_ORG
      value: navikt
    - name: GCS_BUCKET
      value: ghaulp
  envFrom:
    - secret: ghaulp
  gcp:
    buckets:
      - name: ghaulp
  ttlSecondsAfterFinished: 300
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
        - ipv4: 3.68.124.95
        - ipv4: 52.29.238.212
        - ipv4: 3.68.175.98
        - ipv4: 18.159.197.225
        - ipv4: 3.68.124.168
        - ipv4: 3.68.170.153
